spring:
    application: 
        name: spring-redis-demo
    datasource:
        url: jdbc:h2:~/employees
        username: sa
        password: sa
    jpa:
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /h2-console
